language: python
python:
  - "3.6"
cache: pip
services:
  - postgresql
install:
  - pip install pytest
  - pip install pytest-cov
  #- pip install coveralls
  - pip install codecov
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database ml-frontend;' -U postgres
  - psql -c'alter database test owner to dev;' -U postgres

env:       
-DJANGO=3.1.2 DB=postgresql   

script:
  - python manage.py test mlproject
after_success:
  #- coveralls
  - codecov
   
 