llanguage: python
python:
  - "3.6"
cache: pip
install:
  - pip install pytest
  - pip install pytest-cov
  #- pip install coveralls
  - pip install codecov
  - pip install -r requirements.txt
  - pip install Django
  - pip install djangorestframework
  - pip install psycopg2

  
services:
  - postgresql
before_script:
  - psql -c 'create database ml_frontend;' -U postgres
  - psql -c 'create role dev login superuser;' -U postgres
  - psql -c 'alter database ml_frontend owner to dev;' -U postgres
  

env:       
  -DJANGO=3.1.2 DB=postgresql   
script:
  - python src/manage.py test mlproject
after_success:
  #- coveralls
  - codecov

