# Generated by Django 3.2 on 2021-05-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdjan'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userdjan',
            managers=[
            ],
        ),
    ]
