# Generated by Django 3.2 on 2021-05-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userdjan_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdjan',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
