# Generated by Django 3.2 on 2021-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdjan_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdjan',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='userdjan',
            name='staff',
        ),
        migrations.AlterField(
            model_name='userdjan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
