# Generated by Django 3.2 on 2021-05-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210512_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
