version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:latest
        environment:
            POSTGRES_USER: dev
            POSTGRES_DB: ml-frontend
            POSTGRES_PASSWORD: abc123
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install pytest-cov
            pip install codecov
            pip install cryptography
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m       
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py makemigrations
            python3 manage.py migrate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app