# Generated by Django 3.2.3 on 2021-06-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('filename', models.CharField(default='defualt', max_length=300)),
                ('Trained_coefficients', models.JSONField(default=dict)),
            ],
        ),
    ]
