<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-05-30 20:39
=======
# Generated by Django 3.2 on 2021-06-05 09:55
>>>>>>> 48a44c4de5b5a6cec8bdcde9e2d47f0aa6f8e32d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinearRegression', '0002_trainedmodel_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
