# Generated by Django 3.2.3 on 2021-05-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinearRegression', '0002_trainedmodel_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
