# Generated by Django 3.1.2 on 2021-06-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinearRegression', '0003_alter_trainedmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
