# Generated by Django 3.2.3 on 2021-06-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinearRegression', '0003_alter_trainedmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='TestCoeffDetermination',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='TrainCoeffDetermination',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='meanSquaredError',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='Trained_coefficients',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='filename',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='trainedmodel',
            unique_together={('UserId', 'filename')},
        ),
    ]
