# Generated by Django 3.2 on 2021-06-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinearRegression', '0004_auto_20210613_1259'),
        ('LinearRegression', '0004_auto_20210614_1645'),
    ]

    operations = [
    ]
