<<<<<<< HEAD
# Generated by Django 3.2 on 2021-09-26 17:32
=======
# Generated by Django 3.2.7 on 2021-09-27 20:16
>>>>>>> 7de40b4ede04be2a7c8f9e1efa9f77517248d074

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaiveBayes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('filename', models.CharField(max_length=300)),
<<<<<<< HEAD
                ('TrainingAccuracy', models.JSONField(default=dict, null=True)),
                ('TestingAccuracy', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('f1score', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('AUCScore', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
=======
                ('TrainingAccuracy', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('f1score', models.JSONField(default=dict, null=True)),
                ('AUCScore', models.JSONField(default=dict, null=True)),
                ('TestingAccuracy', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True)),
>>>>>>> 7de40b4ede04be2a7c8f9e1efa9f77517248d074
            ],
            options={
                'unique_together': {('UserId', 'filename')},
            },
        ),
    ]
