# Generated by Django 3.2.7 on 2021-09-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaiveBayes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naivebayes',
            name='TestingAccuracy',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
