# Generated by Django 3.2.7 on 2021-09-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaiveBayes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naivebayes',
            name='f1score',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
