# Generated by Django 3.1.2 on 2021-09-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaiveBayes', '0002_naivebayes_f1score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naivebayes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
