# Generated by Django 3.1.2 on 2021-05-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinearRegression', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='filename',
            field=models.CharField(default='defualt', max_length=300),
        ),
    ]
